import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import TanstackProvider from "@/components/Tanstack/TanstackProvider";
import { Toaster } from "react-hot-toast";
// import "bootstrap/dist/js/bootstrap.min.js";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}
